import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { TRPCReactProvider } from "@/trpc/client";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<PropsWithChildren>) => (
  <html lang="en">
    <body className={`${inter.className} antialiased`}>
      <TRPCReactProvider>{children}</TRPCReactProvider>
    </body>
  </html>
);

export default RootLayout;
